import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import './aalto-final.css'
import './aalto-logos-clean.css'
import './aalto-interactions.css'
import './aalto-motion.css'
import './aalto-logo-fouc.css'
import './aalto-mobile-hero-air.css'
import './aalto-mobile-menu-polish.css'
import './aalto-mobile-menu-logo.css'
import './aalto-icon-polish.css'
import './aalto-sector-backgrounds.css'
import './aalto-industries-footer-final.css'
import './aalto-mobile-perfect.css'
import './aalto-final-alignment-fix.css'
import './aalto-ui-modern-polish.css'
import './aalto-homepage-literal-fix.css'
import './aalto-client-logos-final.css'
import './whatsapp-widget.ts'
import './contact-email-fix.ts'
import './contact-form-submit.ts'
import './local-client-logos.ts'
import './industry-popup.ts'
import './aalto-scroll-polish.ts'
import './aalto-final-behavior.ts'
import './mobile-sector-autoplay.ts'
import './mobile-header-controller.ts'
import './aalto-section-reveal.ts'
import App from './AppFixed.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
